model_path: /scratch/mihalcea_root/mihalcea0/smallyan/tofu/data/forget/ft_epoch5_lr2e-05_phi_full_wd0.01/grad_diff_2e-05_full_5
model_family: llama2-7b
model_dir: None

save_dir: ${model_dir}/eval_results/ds_size${ds_size}

#dataset path for each of the 4 datasets to be evaluated
data_path: [locuslab/TOFU, locuslab/TOFU, locuslab/TOFU, locuslab/TOFU]
split: forget10_perturbed
split_list:
  - retain_perturbed
  - real_authors_perturbed
  - world_facts_perturbed
  - ${split}


question_key: [question, question, question, question]
answer_key: [answer, answer, answer, answer]

base_answer_key: [paraphrased_answer, answer, answer, paraphrased_answer]
perturbed_answer_key: [perturbed_answer, perturbed_answer, perturbed_answer, perturbed_answer]

eval_task: [eval_log, eval_real_author_wo_options, eval_real_world_wo_options, eval_log_forget]

generation:
  max_length: 200
  max_new_tokens: null

save_generated_text: true

ds_size: 300

overwrite: true
use_pretrained: false

batch_size: 4
reinitialize_weights: false

retain_result: null

